server:
  port: 8084

spring:
  application:
    name: ApiGateway
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/auth/**
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: UserServiceResilient
          uri: lb://UserService
          predicates:
            - Path=/resilient/users/**
          filters:
            - AuthenticationFilter
        - id: HotelService
          uri: lb://HotelService
          predicates:
            - Path=/hotels/**,/staffs/**
          filters:
            - AuthenticationFilter
        - id: RatingService
          uri: lb://RatingService
          predicates:
            - Path=/ratings/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin123@localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true