server:
  port: 8082

spring:
  application:
    name: HotelService
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: ${HOTEL_DB_URL:jdbc:postgresql://localhost:5432/microservice}
    username: ${HOTEL_DB_USERNAME:postgres}
    password: ${HOTEL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin123@localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true